begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,private,extensions,pg_catalog;
select plan(14);
set local role service_role;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
create temporary table captured_task as select * from public.create_planner_task('One time task',
  private.local_today_for_timezone((select coalesce(timezone,'UTC') from public.profiles where id=auth.uid())));
select lives_ok($q$select public.set_planner_task_scheduled_date(task_id,scheduled_date,updated_at,'Renamed','09:30',true) from captured_task$q$,'task name and time can be edited');
select is((select scheduled_time from public.planner_tasks where id=(select task_id from captured_task)),'09:30','time persisted');
select throws_ok($q$select public.set_planner_task_scheduled_date(task_id,scheduled_date,updated_at) from captured_task$q$,'P0001','task_stale','old versions rejected');
select throws_ok($q$select public.set_planner_task_scheduled_date(id,scheduled_date-1,updated_at) from public.planner_tasks where id=(select task_id from captured_task)$q$,'22023','task_date_in_past','past reschedule rejected');
select public.set_planner_task_completion(id,true,updated_at) from public.planner_tasks where id=(select task_id from captured_task);
select is((select sum(xp_delta)::integer from public.xp_ledger where metadata->>'task_id'=(select task_id::text from captured_task)),private.xp_points_for_completion_source('manual','easy'),'easy goal XP credited');
select public.set_planner_task_completion(id,true,updated_at) from public.planner_tasks where id=(select task_id from captured_task);
select is((select count(*)::integer from public.xp_ledger where metadata->>'task_id'=(select task_id::text from captured_task)),1,'repeated completion does not duplicate XP');
select throws_ok($q$select public.set_planner_task_scheduled_date(id,scheduled_date+1,updated_at) from public.planner_tasks where id=(select task_id from captured_task)$q$,'22023','task_completed','completed tasks cannot move');
select public.set_planner_task_completion(id,false,updated_at) from public.planner_tasks where id=(select task_id from captured_task);
select is((select sum(xp_delta)::integer from public.xp_ledger where metadata->>'task_id'=(select task_id::text from captured_task)),0,'undo reverses XP');
select is((select count(*)::integer from public.xp_ledger where metadata->>'task_id'=(select task_id::text from captured_task) and event_type='goal_achievement'),0,'tasks award no achievement credit');
select public.set_planner_task_scheduled_date(id,scheduled_date,updated_at,null,null,true) from public.planner_tasks where id=(select task_id from captured_task);
select is((select scheduled_time from public.planner_tasks where id=(select task_id from captured_task)),null::text,'optional time can be cleared');
select throws_ok($q$select public.create_planner_task('Past task',(select scheduled_date-1 from captured_task))$q$,'22023','task_date_in_past','new tasks cannot target past days');
create temporary table future_task as select * from public.create_planner_task('Future task',(select scheduled_date+1 from captured_task));
select throws_ok($q$select public.set_planner_task_completion(task_id,true,updated_at) from future_task$q$,'22023','task_completion_in_future','future completions rejected');
select public.set_planner_task_completion(id,true,updated_at) from public.planner_tasks where id=(select task_id from captured_task);
select public.delete_planner_task(task_id) from captured_task;
select is((select sum(xp_delta)::integer from public.xp_ledger where metadata->>'task_id'=(select task_id::text from captured_task)),0,'deletion reverses completion XP');
select set_config('request.jwt.claim.sub','22222222-2222-4222-8222-222222222222',true);
select throws_ok($q$select public.set_planner_task_scheduled_date(task_id,scheduled_date,updated_at) from future_task$q$,'P0001','planner_task_not_found','other owners cannot edit private tasks');
select * from finish();
rollback;
