/** Application chrome supplements semantic theme tokens. CSS expressions are web-only. */
export const PRODUCTION_CHROME = {
  "original": {
    "--gm-page": "var(--background)",
    "--gm-gain": "#10b981",
    "--gm-recover": "#eab308",
    "--gm-warning": "#eab308",
    "--gm-warning-fill": "#fef9c3",
    "--gm-selection": "var(--primary)",
    "--gm-selection-foreground": "var(--primary-foreground)",
    "--gm-today": "var(--gm-heatmap-2)",
    "--gm-today-foreground": "var(--primary-foreground)",
    "--gm-day-selected": "#4687d8",
    "--gm-day-selected-foreground": "#ffffff",
    "--gm-adjacent": "#e4e4e7",
    "--gm-adjacent-foreground": "oklch(0.36 0.01 286)",
    "--gm-stamp-light": "var(--primary)",
    "--gm-heatmap-0": "#ebedf0",
    "--gm-heatmap-1": "#c5ddf7",
    "--gm-heatmap-2": "#7eace6",
    "--gm-heatmap-3": "#0f64bf",
    "--gm-heatmap-4": "#0a458c"
  },
  "original-dark": {
    "--gm-page": "var(--background)",
    "--gm-gain": "#34d399",
    "--gm-recover": "#facc15",
    "--gm-warning": "#facc15",
    "--gm-warning-fill": "color-mix(in srgb, #facc15 22%, var(--background))",
    "--gm-selection": "var(--primary)",
    "--gm-selection-foreground": "var(--primary-foreground)",
    "--gm-today": "var(--gm-heatmap-4)",
    "--gm-today-foreground": "var(--primary-foreground)",
    "--gm-day-selected": "#7eace6",
    "--gm-day-selected-foreground": "#0b1f38",
    "--gm-adjacent": "#3f3f46",
    "--gm-adjacent-foreground": "oklch(0.92 0.003 286)",
    "--gm-stamp-light": "var(--primary)",
    "--gm-heatmap-0": "#2a2f36",
    "--gm-heatmap-1": "#163a63",
    "--gm-heatmap-2": "#245ea6",
    "--gm-heatmap-3": "#4687d8",
    "--gm-heatmap-4": "#7eace6"
  },
  "gazetteer": {
    "--gm-page": "#f3ead8",
    "--gm-gain": "#4a6740",
    "--gm-recover": "#eab308",
    "--gm-warning": "#eab308",
    "--gm-warning-fill": "#fef9c3",
    "--gm-selection": "#6f8175",
    "--gm-selection-foreground": "#f8f1e3",
    "--gm-today": "var(--gm-heatmap-1)",
    "--gm-today-foreground": "var(--foreground)",
    "--gm-day-selected": "color-mix(in srgb, var(--gm-selection) 28%, var(--background))",
    "--gm-day-selected-foreground": "var(--foreground)",
    "--gm-adjacent": "#d4d4d8",
    "--gm-adjacent-foreground": "oklch(0.36 0.01 286)",
    "--gm-stamp-light": "#c88968",
    "--gm-heatmap-0": "#efe4d0",
    "--gm-heatmap-1": "color-mix(in srgb, var(--primary) 28%, var(--background))",
    "--gm-heatmap-2": "var(--gm-stamp-light)",
    "--gm-heatmap-3": "var(--primary)",
    "--gm-heatmap-4": "#6e341c"
  },
  "gazetteer-dark": {
    "--gm-page": "#1c1610",
    "--gm-gain": "#8aa37a",
    "--gm-recover": "#facc15",
    "--gm-warning": "#facc15",
    "--gm-warning-fill": "color-mix(in srgb, #facc15 22%, var(--background))",
    "--gm-selection": "#8aa396",
    "--gm-selection-foreground": "#1c1610",
    "--gm-today": "var(--gm-heatmap-1)",
    "--gm-today-foreground": "var(--foreground)",
    "--gm-day-selected": "color-mix(in srgb, var(--gm-selection) 70%, var(--background))",
    "--gm-day-selected-foreground": "var(--foreground)",
    "--gm-adjacent": "#52525b",
    "--gm-adjacent-foreground": "oklch(0.92 0.003 286)",
    "--gm-stamp-light": "#8a5a40",
    "--gm-heatmap-0": "#2a2218",
    "--gm-heatmap-1": "color-mix(in srgb, var(--gm-stamp-light) 70%, var(--background))",
    "--gm-heatmap-2": "var(--gm-stamp-light)",
    "--gm-heatmap-3": "var(--primary)",
    "--gm-heatmap-4": "#e2c4b0"
  }
} as const;
