import { fontStack } from "./fonts";
import {
  APP_COLOR_ROLES,
  colorRoleUtility,
  colorRoleVariable,
  SCALE_COLOR_ROLES,
  SURFACE_COLOR_ROLES,
  type ColorRole,
  type ThemeColors,
  type ThemeDefinition,
} from "./roles";
import { THEMES } from "./themes";

const COLOR_ROLES: readonly ColorRole[] = [
  ...SURFACE_COLOR_ROLES,
  ...APP_COLOR_ROLES,
  ...SCALE_COLOR_ROLES,
];

const HEADER = `/*
 * Generated by \`pnpm themes:css\` from packages/shared/src/brand.
 * Edit the theme definitions there and regenerate; do not edit by hand.
 */`;

function block(selectors: string[], declarations: string[]) {
  return `${selectors.join(",\n")} {\n${declarations.map((line) => `  ${line};`).join("\n")}\n}`;
}

function colorDeclarations(colors: ThemeColors) {
  return COLOR_ROLES.map((role) => `${colorRoleVariable(role)}: ${colors[role]}`);
}

function tailwindTheme() {
  return block(
    ["@theme inline"],
    [
      ...[...SURFACE_COLOR_ROLES, ...APP_COLOR_ROLES].map(
        (role) => `--color-${colorRoleUtility(role)}: var(${colorRoleVariable(role)})`
      ),
      "--font-sans: var(--font-app-sans)",
      "--font-mono: var(--font-app-mono)",
      "--font-display: var(--font-app-display)",
    ]
  );
}

function themeBlocks(theme: ThemeDefinition, isDefault: boolean) {
  const scope = `[data-ui-style="${theme.id}"]`;
  const blocks = [
    block(isDefault ? [":root", scope] : [scope], [
      `--radius: ${theme.radiusRem}rem`,
      ...colorDeclarations(theme.colors),
      `--font-app-sans: ${fontStack(theme.fonts.sans)}`,
      `--font-app-display: ${fontStack(theme.fonts.display)}`,
      `--font-app-mono: ${fontStack(theme.fonts.mono)}`,
      `--gm-landing-atmosphere: ${theme.effects.landingAtmosphere}`,
    ]),
  ];
  if (theme.darkColors) {
    blocks.push(
      block(isDefault ? [".dark", `.dark${scope}`] : [`.dark${scope}`], colorDeclarations(theme.darkColors))
    );
  }
  return blocks;
}

/**
 * The web stylesheet for every theme. A theme applies to `<html>` or any
 * subtree through `data-ui-style="<id>"`; the first theme is also `:root`.
 */
export function renderThemeCss(themes: readonly ThemeDefinition[] = THEMES): string {
  return `${[
    HEADER,
    tailwindTheme(),
    ...themes.flatMap((theme, index) => themeBlocks(theme, index === 0)),
  ].join("\n\n")}\n`;
}
