import { fontStack } from "./fonts";
import {
  APP_COLOR_ROLES,
  colorRoleUtility,
  colorRoleVariable,
  SCALE_COLOR_ROLES,
  SURFACE_COLOR_ROLES,
  TEXT_ROLES,
  type ColorRole,
  type TextRole,
  type ThemeColors,
  type ThemeDefinition,
} from "./roles";
import { THEMES } from "./themes";

const COLOR_ROLES: readonly ColorRole[] = [
  ...SURFACE_COLOR_ROLES,
  ...APP_COLOR_ROLES,
  ...SCALE_COLOR_ROLES,
];

const HEADER = `/*
 * Generated by \`pnpm themes:css\` from packages/shared/src/brand.
 * Edit the theme definitions there and regenerate; do not edit by hand.
 */`;

function block(selectors: string[], declarations: string[]) {
  return `${selectors.join(",\n")} {\n${declarations.map((line) => `  ${line};`).join("\n")}\n}`;
}

function colorDeclarations(colors: ThemeColors) {
  return COLOR_ROLES.map((role) => `${colorRoleVariable(role)}: ${colors[role]}`);
}

function textDeclarations(theme: ThemeDefinition) {
  return [
    ...TEXT_ROLES.flatMap((role) => [
      `--type-${role}-font: var(--font-app-${theme.text[role].slot})`,
      `--type-${role}-weight: ${theme.text[role].weight}`,
    ]),
    `--type-eyebrow-tracking: ${theme.text.eyebrow.trackingEm}em`,
  ];
}

const TEXT_ROLE_EXTRAS: Partial<Record<TextRole, string[]>> = {
  eyebrow: ["letter-spacing: var(--type-eyebrow-tracking)", "text-transform: uppercase"],
  stat: ["font-variant-numeric: tabular-nums"],
};

function textUtilities() {
  return TEXT_ROLES.map((role) =>
    block(
      [`@utility type-${role}`],
      [
        `font-family: var(--type-${role}-font)`,
        `font-weight: var(--type-${role}-weight)`,
        ...(TEXT_ROLE_EXTRAS[role] ?? []),
      ]
    )
  );
}

function tailwindTheme() {
  return block(
    ["@theme inline"],
    [
      ...[...SURFACE_COLOR_ROLES, ...APP_COLOR_ROLES].map(
        (role) => `--color-${colorRoleUtility(role)}: var(${colorRoleVariable(role)})`
      ),
      "--font-sans: var(--font-app-sans)",
      "--font-mono: var(--font-app-mono)",
      "--font-display: var(--font-app-display)",
    ]
  );
}

function themeBlocks(theme: ThemeDefinition, isDefault: boolean) {
  const scope = `[data-ui-style="${theme.id}"]`;
  const blocks = [
    block(isDefault ? [":root", scope] : [scope], [
      `--radius: ${theme.radiusRem}rem`,
      ...colorDeclarations(theme.colors),
      `--font-app-sans: ${fontStack(theme.fonts.sans)}`,
      `--font-app-display: ${fontStack(theme.fonts.display)}`,
      `--font-app-mono: ${fontStack(theme.fonts.mono)}`,
      ...textDeclarations(theme),
      `--gm-landing-atmosphere: ${theme.effects.landingAtmosphere}`,
    ]),
  ];
  if (theme.darkColors) {
    blocks.push(
      block(isDefault ? [".dark", `.dark${scope}`] : [`.dark${scope}`], colorDeclarations(theme.darkColors))
    );
  }
  return blocks;
}

/**
 * The web stylesheet for every theme. A theme applies to `<html>` or any
 * subtree through `data-ui-style="<id>"`; the first theme is also `:root`.
 */
export function renderThemeCss(themes: readonly ThemeDefinition[] = THEMES): string {
  return `${[
    HEADER,
    tailwindTheme(),
    ...textUtilities(),
    ...themes.flatMap((theme, index) => themeBlocks(theme, index === 0)),
  ].join("\n\n")}\n`;
}
