import { FONTS, fontStack, type FontDefinition } from "./fonts";
import {
  APP_COLOR_ROLES,
  colorRoleUtility,
  colorRoleVariable,
  SCALE_COLOR_ROLES,
  SURFACE_COLOR_ROLES,
  TEXT_ROLES,
  type ColorRole,
  type TextRole,
  type ThemeColors,
  type ThemeDefinition,
} from "./roles";
import { THEMES } from "./themes";

const COLOR_ROLES: readonly ColorRole[] = [
  ...SURFACE_COLOR_ROLES,
  ...APP_COLOR_ROLES,
  ...SCALE_COLOR_ROLES,
];

const HEADER = `/*
 * Generated by \`pnpm themes:css\` from packages/shared/src/brand.
 * Edit the theme definitions there and regenerate; do not edit by hand.
 */`;

function block(selectors: string[], declarations: string[]) {
  return `${selectors.join(",\n")} {\n${declarations.map((line) => `  ${line};`).join("\n")}\n}`;
}

function colorDeclarations(colors: ThemeColors) {
  return COLOR_ROLES.map((role) => `${colorRoleVariable(role)}: ${colors[role]}`);
}

function textDeclarations(theme: ThemeDefinition) {
  return [
    ...TEXT_ROLES.flatMap((role) => [
      `--type-${role}-font: var(--font-app-${theme.text[role].slot})`,
      `--type-${role}-weight: ${theme.text[role].weight}`,
    ]),
    `--type-eyebrow-tracking: ${theme.text.eyebrow.trackingEm}em`,
  ];
}

const TEXT_ROLE_EXTRAS: Partial<Record<TextRole, string[]>> = {
  eyebrow: ["letter-spacing: var(--type-eyebrow-tracking)", "text-transform: uppercase"],
  stat: ["font-variant-numeric: tabular-nums"],
  figure: ["font-variant-numeric: tabular-nums"],
};

function textUtilities() {
  return TEXT_ROLES.map((role) =>
    block(
      [`@utility type-${role}`],
      [
        `font-family: var(--type-${role}-font)`,
        `font-weight: var(--type-${role}-weight)`,
        ...(TEXT_ROLE_EXTRAS[role] ?? []),
      ]
    )
  );
}

function tailwindTheme() {
  return block(
    ["@theme inline"],
    [
      ...[...SURFACE_COLOR_ROLES, ...APP_COLOR_ROLES].map(
        (role) => `--color-${colorRoleUtility(role)}: var(${colorRoleVariable(role)})`
      ),
      "--font-sans: var(--font-app-sans)",
      "--font-mono: var(--font-app-mono)",
      "--font-display: var(--font-app-display)",
    ]
  );
}

function themeBlock(theme: ThemeDefinition, selectors: string[]) {
  return block(selectors, [
    `--radius: ${theme.radiusRem}rem`,
    ...colorDeclarations(theme.colors),
    `--font-app-sans: ${fontStack(theme.fonts.sans)}`,
    `--font-app-display: ${fontStack(theme.fonts.display)}`,
    `--font-app-mono: ${fontStack(theme.fonts.mono)}`,
    ...textDeclarations(theme),
    `--gm-landing-atmosphere: ${theme.effects.landingAtmosphere}`,
    `color-scheme: ${theme.appearance}`,
  ]);
}

/**
 * The web stylesheet, generated into src/app/themes.css: Tailwind's mapping,
 * the text-role utilities, and every live theme. A theme applies to `<html>`
 * or any subtree through `data-ui-style="<id>"`; the first theme is also
 * `:root`. The web app has no dark mode, so `darkColors` are native-only.
 */
export function renderThemeCss(themes: readonly ThemeDefinition[] = THEMES): string {
  const live = themes.filter((theme) => theme.status === "live");
  return `${[
    HEADER,
    tailwindTheme(),
    ...textUtilities(),
    ...live.map((theme, index) => {
      const scope = `[data-ui-style="${theme.id}"]`;
      return themeBlock(theme, index === 0 ? [":root", scope] : [scope]);
    }),
  ].join("\n\n")}\n`;
}

/**
 * Study skins' theme blocks and font variables, injected by the provider.
 * Only the selected skin's faces are loaded from Google Fonts. The
 * `:root[...]` selector outranks the default theme's `:root` wherever the
 * injected sheet lands in the cascade.
 */
export function renderStudyThemeCss(themes: readonly ThemeDefinition[] = THEMES): string {
  const faces = Object.values(FONTS as Record<string, FontDefinition>)
    .filter((font) => font.googleWeights)
    .map((font) => `${font.cssVariable}: "${font.family}"`);
  return [
    block([":root"], faces),
    ...themes
      .filter((theme) => theme.status === "study")
      .map((theme) => {
        const scope = `[data-ui-style="${theme.id}"]`;
        return themeBlock(theme, [`:root${scope}`, scope]);
      }),
  ].join("\n");
}
