import Link from "next/link";
import { httpRoutes, operationMetadata } from "@/lib/external-tools/catalog";

export default function DevelopersPage() {
  return <main className="mx-auto max-w-4xl space-y-10 px-6 py-16">
    <header className="space-y-4"><Link href="/" className="text-sm text-muted-foreground">Goalmaxxing</Link><h1 className="font-display text-4xl">Bring your own assistant</h1><p className="max-w-2xl text-lg text-muted-foreground">Connect your AI assistant to your goals and plans. Your assistant does the reasoning; Goalmaxxing keeps the record and applies its account rules.</p></header>
    <section className="space-y-3"><h2 className="font-display text-2xl">Connect with MCP</h2><p>Add your Goalmaxxing origin followed by <code>/api/mcp</code> as a remote HTTP MCP server. Choose OAuth, sign in, and approve account access. Disconnect from Settings → Integrations.</p><p className="text-sm text-muted-foreground">Availability depends on the assistant’s support for custom tools. ChatGPT and Claude support remote integrations; Gemini CLI supports MCP. Browser agents can use the Goalmaxxing website directly.</p></section>
    <section className="space-y-3"><h2 className="font-display text-2xl">Use the account API</h2><p>Send a bearer access token to <code>/api/v1</code>. <Link href="/api/v1/openapi.json" className="underline">Download the OpenAPI contract</Link> for input schemas and authentication endpoints. Writes accept structured fields and never invoke Goalmaxxing AI.</p><p className="text-sm text-muted-foreground">Account connections grant read and write access to your account data. The initial release uses existing account permissions. Cookie-only requests and service credentials are rejected.</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="py-3 pr-4">Method</th><th className="py-3 pr-4">Endpoint</th><th className="py-3">Action</th></tr></thead><tbody>{httpRoutes.map(route => <tr key={`${route.method}:${route.path}`} className="border-b"><td className="py-3 pr-4 font-mono text-xs">{route.method}</td><td className="py-3 pr-4 font-mono text-xs">/api/v1{route.path}</td><td className="py-3">{operationMetadata[route.operation].title}</td></tr>)}</tbody></table></div>
    </section>
    <section className="space-y-3"><h2 className="font-display text-2xl">Make changes deliberately</h2><p>Use a stable requestId when creating goals or tasks and retry with the same input. Read a goal before replacing its definition, and supply its updated_at as expectedUpdatedAt. Preview a plan, review the changes, then submit its returned publishRequest after approval.</p><p>Errors include a code, message, and correlation ID. A stale-state error means you should refresh and review the change again before applying it.</p></section>
  </main>;
}
