import type { GoalCreationFields } from "@/features/goals/goal-creation-model";

export const MATERIALS = [
  { id: "glass", form: "solid", name: "Liquid Glass", tag: "01 / Optical · 3D", premise: "A translucent object with a polished rim. Color lives within its thickness; the commitment floats just above it.", detail: "Pointer light, a continuous polished edge, and softly raised target text. A milky reading layer keeps small type grounded.", use: "A single featured goal or the active folio card.", tradeoff: "The most luminous option; blur and transparency need careful contrast and device checks." },
  { id: "ceramic", form: "solid", name: "Ceramic Relief", tag: "02 / Sculptural · 3D", premise: "A substantial, glazed tile. Softly rounded corners, a thick colored edge, and raised numerals you almost want to touch.", detail: "A richer category glaze and a continuous edge give the tile weight. The number and rhythm cast soft shadows onto its face.", use: "The strongest starting point for everyday goal cards.", tradeoff: "Tactile without blur; keep the depth restrained in dense layouts." },
  { id: "diorama", form: "layered", name: "Layered Diorama", tag: "03 / Spatial · 3D", premise: "A miniature paper sculpture. Separate planes of color, type, and detail reveal themselves as the card turns.", detail: "A recessed backplate, offset paper sheets, and floating typography create real separation between layers.", use: "Folio browsing and a focused goal preview.", tradeoff: "The most expressive silhouette; needs breathing room and a flatter list treatment." },
  { id: "foil", form: "solid", name: "Foil Print", tag: "04 / Iridescent · 3D", premise: "A collectible printed card. A narrow spectral sheen catches the light across deep ink and a finely ruled frame.", detail: "The original pearlescent coating and foil numerals, now on a single thick card with a gilded edge and gentle perspective tilt.", use: "Completed goals and special collection moments.", tradeoff: "A celebratory treatment; too much foil would make everyday planning noisy." },
  { id: "woven", form: "flat", name: "Woven Paper", tag: "05 / Textile · Surface", premise: "Warm, quiet, and kept for years. Cloth fibers, an inset stitched border, and printed category color feel like a personal archive.", detail: "Fine crosshatching and an inked target replace shine with tactility. A calm match for the folio’s cloth cover.", use: "Past goals, long reading sessions, and the warmest everyday direction.", tradeoff: "The least flashy option; texture must stay subtle behind small text." },
  { id: "pearl", form: "solid", name: "Pearl Reserve", tag: "06 / Pearlescent · New · 3D", premise: "An ivory invitation, kept like a precious object. Warm pearl lacquer, champagne foil, and a finely gilded edge catch the light without turning dark.", detail: "Inspired by fine stationery and mother-of-pearl. A luminous ivory face holds embossed bronze-gold numerals and a quiet prismatic wash.", use: "A light premium alternative for everyday goals and completed collections.", tradeoff: "The most restrained foil direction; metallic accents need enough depth to stay legible on ivory." },
  { id: "guilloche", form: "solid", name: "Midnight Guilloché", tag: "07 / Engraved · New · 3D", premise: "The precision of a watch dial. Midnight blue enamel, hairline silver, and concentric engraved curves make the goal feel like a crafted instrument.", detail: "A fine engine-turned pattern sits inside a polished frame. Cool silver numerals and a machined rim contrast with deep enamel.", use: "Focused commitments and collections with a cooler, more architectural personality.", tradeoff: "Fine engraving is deliberately faint; essential text stays on the calm center of the dial." },
  { id: "atelier", form: "solid", name: "Oxblood Atelier", tag: "08 / Leather & gold · New · 3D", premise: "A small leather-bound edition. Rich oxblood, discreet grain, and hot-stamped gold bring the warmth of a bookbinder’s workshop to a single card.", detail: "Blind-tooled borders, a softly burnished corner, and brass lettering. One solid leather edge gives it weight without a stack of pages.", use: "Personal archives and long commitments that deserve a keepsake.", tradeoff: "Warm and formal; category color appears subtly in the leather instead of dominating the face." },
] as const;

export type CardMaterial = (typeof MATERIALS)[number];

const BASE: GoalCreationFields = {
  title: "Make time for the long run.", description: "", category_selection: "health", custom_category: "", color: "#10b981",
  frequency_type: "recurring", recurrence_interval: "weekly", target_count: "3", target_basis: "period", milestone_names: [],
  start_date: "2026-06-01", end_date: "2026-09-01", default_local_time: "", difficulty: "medium", is_private: false, linked_target_goal_id: "none",
};

export const MATERIAL_SAMPLES: { label: string; fields: GoalCreationFields }[] = [
  { label: "Health / green", fields: BASE },
  { label: "Career / violet", fields: { ...BASE, title: "Build something worth sharing.", category_selection: "career", color: "#8b5cf6", target_count: "12", target_basis: "lifetime", difficulty: "hard" } },
  { label: "Personal / rose", fields: { ...BASE, title: "A little more room for the things that make me feel like myself.", category_selection: "personal", color: "#f43f5e", target_count: "1", recurrence_interval: "daily", difficulty: "easy" } },
];
