import type { GoalCreationFields } from "@/features/goals/goal-creation-model";

export const MATERIALS = [
  { id: "glass", form: "solid", name: "Liquid Glass", tag: "01 / Optical · 3D", premise: "A translucent object with a polished rim. Color lives within its thickness; every mark rises subtly from the same face.", detail: "Pointer light, a continuous polished edge, and shallow relief type. A milky reading layer keeps small lettering grounded in the glass.", use: "A single featured goal or the active folio card.", tradeoff: "The most luminous option; blur and transparency need careful contrast and device checks." },
  { id: "ceramic", form: "solid", name: "Ceramic Relief", tag: "02 / Sculptural · 3D", premise: "A substantial, glazed tile. Softly rounded corners, a thick colored edge, and raised numerals you almost want to touch.", detail: "A richer category glaze and a continuous edge give the tile weight. The number and rhythm cast soft shadows onto its face.", use: "The strongest starting point for everyday goal cards.", tradeoff: "Tactile without blur; keep the depth restrained in dense layouts." },
  { id: "diorama", form: "layered", name: "Layered Diorama", tag: "03 / Spatial · 3D", premise: "A miniature paper sculpture. Separate sheets reveal themselves as the card turns, while the lettering stays pressed into its top face.", detail: "A recessed backplate and offset paper sheets create separation behind one readable embossed surface.", use: "Folio browsing and a focused goal preview.", tradeoff: "The most expressive silhouette; needs breathing room and a flatter list treatment." },
  { id: "foil", form: "solid", name: "Foil Print", tag: "04 / Iridescent · 3D", premise: "A collectible printed card. A narrow spectral sheen catches the light across deep ink and a finely ruled frame.", detail: "The original pearlescent coating and foil numerals on a solid gilded card. A narrow reflection travels across the face as its sides turn through the light.", use: "Completed goals and special collection moments.", tradeoff: "A celebratory treatment; too much foil would make everyday planning noisy." },
  { id: "woven", form: "flat", name: "Woven Paper", tag: "05 / Textile · Surface", premise: "Warm, quiet, and kept for years. Cloth fibers, an inset stitched border, and printed category color feel like a personal archive.", detail: "Fine crosshatching and an inked target replace shine with tactility. A calm match for the folio’s cloth cover.", use: "Past goals, long reading sessions, and the warmest everyday direction.", tradeoff: "The least flashy option; texture must stay subtle behind small text." },
  { id: "pearl", form: "solid", name: "Pearl Reserve", tag: "06 / Pearlescent · New · 3D", premise: "An ivory invitation, kept like a precious object. Warm pearl lacquer, champagne foil, and a finely gilded edge catch the light without turning dark.", detail: "Inspired by fine stationery and mother-of-pearl. A luminous ivory face holds embossed bronze-gold numerals and a quiet prismatic wash.", use: "A light premium alternative for everyday goals and completed collections.", tradeoff: "The most restrained foil direction; metallic accents need enough depth to stay legible on ivory." },
  { id: "ruby", form: "solid", name: "Ruby Cabochon", tag: "07 / Ruby & rose gold · New · 3D", premise: "A polished ruby held in rose gold. Deep cherry color gathers at the edges while a soft, bright reflection rolls across the face.", detail: "A smooth gemstone direction: luminous red lacquer, a narrow rose-gold setting, and raised champagne lettering. The light follows the same tilt as the stone.", use: "A jewel-like keepsake for a meaningful goal or completed collection.", tradeoff: "Rich and warm; the central reading surface stays darker than the reflective edges." },
  { id: "sapphire", form: "solid", name: "Sapphire Prism", tag: "08 / Sapphire & platinum · New · 3D", premise: "A cut sapphire in a platinum setting. Crisp blue facets and silver type catch a narrow ribbon of light as you turn it.", detail: "Angular reflections live around a calm midnight-blue center. Cyan corner facets, polished sides, and a moving specular line give the card a cut-crystal character.", use: "A cooler, more precise gemstone alternative to Ruby and Foil.", tradeoff: "Facets stay near the frame so small labels and long goal titles remain clear." },
  { id: "platinum", form: "solid", name: "Platinum Mirror", tag: "09 / Polished platinum · New · 3D", premise: "A bright, cool piece of precious metal. A mirror-polished rim, satin silver face, and graphite-metal numerals make a lighter kind of statement.", detail: "A broad silver reflection moves with the tilt, while fine brushed grain gives the center a quieter finish. Dark etched lettering keeps the face readable.", use: "A light metallic counterpart to Foil Print and a cooler alternative to Pearl.", tradeoff: "The shine is strongest around the rim; the reading area stays satin rather than fully mirrored." },
  { id: "prismatic", form: "solid", name: "Prismatic Pearl", tag: "10 / Category pearl · New · 3D", premise: "Pearl without a signature hue. A warm white shell catches faint pools of your goal’s color, shifting softly as you turn it.", detail: "The category tints the opalescent wash, fine rim, and embossed numerals. Gentle moving color takes the place of a shine beam.", use: "A light premium finish that keeps the category recognizable.", tradeoff: "Deliberately subtle; choose another sample goal to compare the tinted reflections." },
  { id: "chromatic", form: "solid", name: "Chromatic Foil", tag: "11 / Category foil · New · 3D", premise: "A dark collectible with your goal’s own light. Graphite holds the face while category-colored foil shines through the frame and lettering.", detail: "A clean reflection sweeps over a smoke-metal surface. The edge, foil numerals, and luminous ribbon all borrow their tint from the goal.", use: "The richest category-aware counterpart to the original Foil Print.", tradeoff: "The dark face stays neutral so even strong category colors retain readable pale lettering." },
  { id: "alloy", form: "solid", name: "Anodized Alloy", tag: "12 / Category metal · New · 3D", premise: "A single piece of finely brushed metal, colored by the goal itself. Cool satin depth and a polished edge feel precise and substantial.", detail: "Category color is infused into the metal instead of printed on top. A broad soft reflection crosses the grain, with darker engraved numerals for clarity.", use: "An everyday premium card with a more visible category color.", tradeoff: "More color than Pearl and less spectacle than Foil; the brushed center softens the shine." },
] as const;

export type CardMaterial = (typeof MATERIALS)[number];

const BASE: GoalCreationFields = {
  title: "Make time for the long run.", description: "", category_selection: "health", custom_category: "", color: "#10b981",
  frequency_type: "recurring", recurrence_interval: "weekly", target_count: "3", target_basis: "period", milestone_names: [],
  start_date: "2026-06-01", end_date: "2026-09-01", default_local_time: "", difficulty: "medium", is_private: false, linked_target_goal_id: "none",
};

export const MATERIAL_SAMPLES: { label: string; fields: GoalCreationFields }[] = [
  { label: "Health / green", fields: BASE },
  { label: "Career / violet", fields: { ...BASE, title: "Build something worth sharing.", category_selection: "career", color: "#8b5cf6", target_count: "12", target_basis: "lifetime", difficulty: "hard" } },
  { label: "Personal / rose", fields: { ...BASE, title: "A little more room for the things that make me feel like myself.", category_selection: "personal", color: "#f43f5e", target_count: "1", recurrence_interval: "daily", difficulty: "easy" } },
];
