import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronDown, ChevronUp, X } from "lucide-react";
import { Dialog, DialogContent, DialogTitle, DialogDescription, DialogClose } from "@/components/ui/dialog";
import { CATEGORIES, defaultDraft, draftError, type GoalDraft } from "./model";
import { GOAL_CREATE_KIND_HELP, type GoalCreateKind } from "@/lib/goals/form-options";
import type { Lab } from "./use-lab";
export function GoalBuilder({ s }: { s: Lab }) {
  if (!s.creating) return null;
  if (s.concept === "glide") return <Dialog open onOpenChange={v => { if (!v) s.setCreating(false); }}><DialogContent className="il-dialog il-builder-dialog il-theme-glide" overlayClassName="il-overlay" showCloseButton={false}><div className="il-section-heading"><DialogTitle>A new beginning</DialogTitle><DialogClose className="il-icon" aria-label="Close goal creation"><X size={19}/></DialogClose></div><DialogDescription>Make a goal that fits your life. Review everything before adding it.</DialogDescription><BuilderForm s={s}/></DialogContent></Dialog>;
  return <section className={`il-builder il-theme-${s.concept}`} aria-label="Create a goal"><div className="il-section-heading"><div><span className="il-eyebrow">{s.concept === "fold" ? "Build it right here" : "New goal / setup"}</span><h2>A new beginning</h2></div><button className="il-icon" aria-label="Close goal creation" onClick={() => s.setCreating(false)}><X size={19}/></button></div><BuilderForm s={s}/></section>;
}
function BuilderForm({ s }: { s: Lab }) {
  const [d, setD] = useState<GoalDraft>(() => defaultDraft(s.date));
  const [step, setStep] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const patch = (p: Partial<GoalDraft>) => { setD(old => ({...old,...p})); setError(null); };
  const steps = ["Intention", "Shape", "Details", "Review"];
  const reorder = (i: number, direction: number) => { const names = d.milestones.split("\n"); const target = i+direction; if (target < 0 || target >= names.length) return; [names[i],names[target]]=[names[target],names[i]]; patch({milestones:names.join("\n")}); };
  const advance = () => { if (step === 0 && !d.title.trim()) { setError("Give it a name to continue."); return; } if (step === 2 && draftError(d)) { setError(draftError(d)); return; } setStep(step+1); };
  return <form onSubmit={e => { e.preventDefault(); if (step < 3) advance(); else { const issue=draftError(d); if (issue) setError(issue); else s.create(d); } }}>
    <nav className="il-builder-steps" aria-label="Goal creation steps">{steps.map((name,i) => <button key={name} type="button" aria-current={i===step ? "step" : undefined} disabled={i>step} onClick={() => setStep(i)}><span>{i<step ? <Check size={12}/> : i+1}</span>{name}</button>)}</nav>
    <div className="il-builder-body" key={step}>
    {step===0 && <><h3>What would you like to make room for?</h3><label>Name<input autoFocus value={d.title} placeholder="e.g. Learn to play piano" onChange={e => patch({title:e.target.value})}/></label><fieldset><legend>What kind of thing is it?</legend><div className="il-type-choices">{(["recurring","fixed_milestones","planner_task"] as GoalCreateKind[]).map(kind => <button type="button" key={kind} aria-pressed={kind===d.kind} onClick={() => patch({kind})}><strong>{kind==="recurring" ? "A rhythm" : kind==="fixed_milestones" ? "A set of milestones" : "A one-time task"}</strong><span>{GOAL_CREATE_KIND_HELP[kind]}</span></button>)}</div></fieldset></>}
    {step===1 && <><h3>{d.kind==="fixed_milestones" ? "Give the steps a shape." : d.kind==="planner_task" ? "Keep it simple." : "Choose a rhythm, not a rigid rule."}</h3>{d.kind==="recurring" ? <><div className="il-form-grid"><label>Frequency<select value={d.interval} onChange={e => patch({interval:e.target.value as GoalDraft["interval"]})}><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></label><label>Target basis<select value={d.basis} onChange={e => patch({basis:e.target.value as GoalDraft["basis"]})}><option value="period">Per period</option><option value="lifetime">Over the goal’s lifetime</option></select></label></div><label>Target completions<input type="number" min="1" max="99" value={d.target} onChange={e => patch({target:Number(e.target.value)})}/></label><p className="il-builder-summary">{d.target} completions {d.basis === "lifetime" ? "in total" : `per ${d.interval === "daily" ? "day" : d.interval === "weekly" ? "week" : "month"}`}. You can move the planned occurrences as life changes.</p></> : d.kind==="fixed_milestones" ? <><label>Milestones · one per line<textarea rows={4} value={d.milestones} onChange={e => patch({milestones:e.target.value})}/></label><ol className="il-milestone-editor">{d.milestones.split("\n").map((name,i,all) => <li key={i}><span>{i+1}. {name || "Unnamed step"}</span><button type="button" className="il-icon" aria-label={`Move milestone ${i+1} up`} disabled={i===0} onClick={() => reorder(i,-1)}><ChevronUp size={16}/></button><button type="button" className="il-icon" aria-label={`Move milestone ${i+1} down`} disabled={i===all.length-1} onClick={() => reorder(i,1)}><ChevronDown size={16}/></button></li>)}</ol></> : <p>This is a one-time planner task. It starts in Unplanned, ready to place on any date. It does not become a recurring goal.</p>}</>}
    {step===2 && <><h3>A few details, on your terms.</h3><div className="il-form-grid"><label>Start date<input type="date" value={d.start} onChange={e => patch({start:e.target.value})}/></label><label>End date · optional<input type="date" min={d.start} value={d.end} onChange={e => patch({end:e.target.value})}/></label></div>{d.kind!=="planner_task" && <><label>Category<select value={d.category} onChange={e => patch({category:e.target.value})}>{CATEGORIES.map(c => <option key={c}>{c}</option>)}</select></label><label className="il-checkbox-label"><input type="checkbox" checked={d.private} onChange={e => patch({private:e.target.checked})}/>Keep this goal private</label><details><summary>More options · difficulty, reward, team, linked goal</summary><div className="il-form-grid"><label>Difficulty<select value={d.difficulty} onChange={e => patch({difficulty:e.target.value as GoalDraft["difficulty"]})}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label>Team<select value={d.team} onChange={e => patch({team:e.target.value})}><option value="">Personal</option><option>Small Steps Club</option></select></label></div><label>Reward<input value={d.reward} onChange={e => patch({reward:e.target.value})} placeholder="Something to look forward to"/></label><label>Also credit this goal when completed<select value={d.linkedTo} onChange={e => patch({linkedTo:e.target.value})}><option value="">No linked goal</option>{s.data.goals.filter(g => !g.linkedTo).map(g => <option key={g.id} value={g.id}>{g.title}</option>)}</select></label></details></>}</>}
    {step===3 && <><h3>Looks like a good beginning.</h3><div className="il-creation-preview"><span className="il-eyebrow">{d.kind==="planner_task" ? "One-time task" : d.category}</span><h2>{d.title}</h2><p>{d.kind==="recurring" ? `${d.target} completions · ${d.interval} · ${d.basis === "lifetime" ? "lifetime target" : "per period"}` : d.kind==="fixed_milestones" ? `${d.milestones.split("\n").filter(x => x.trim()).length} milestones` : "One task in Unplanned"}</p>{d.kind==="fixed_milestones" && <ol>{d.milestones.split("\n").filter(x => x.trim()).map((n,i) => <li key={i}>{n}</li>)}</ol>}<p>{d.start}{d.end ? ` → ${d.end}` : " · No end date"}</p>{d.kind!=="planner_task" && <p>{d.private ? "Private" : "Visible to your people"} · {d.team || "Personal"} · {d.difficulty}{d.reward ? ` · Reward: ${d.reward}` : ""}{d.linkedTo ? ` · Also credits ${s.data.goals.find(g => g.id===d.linkedTo)?.title}` : ""}</p>}</div><p>The first occurrence or milestones go into Unplanned. Nothing is scheduled automatically in this study.</p><button className="il-text-button" type="button" onClick={() => setStep(0)}>Edit this goal</button></>}
    </div>{error && <p role="alert" className="il-form-error">{error}</p>}<div className="il-actions"><button type="button" className="il-secondary" onClick={() => step ? setStep(step-1) : s.setCreating(false)}><ArrowLeft size={15}/>{step ? "Back" : "Cancel"}</button><button className="il-primary" type="submit">{step===3 ? "Create in demo" : "Continue"}{step===3 ? <Check size={16}/> : <ArrowRight size={16}/>}</button></div>
  </form>;
}
