import type { ThemeDefinition } from "../roles";

/**
 * The surveyor's ledger: warm paper, walnut ink, stamp rust, sage highlight,
 * Newsreader names, Source Sans 3 labels, IBM Plex Mono figures, Nest marks.
 *
 * Native reads the surface roles plus page/gain/recover, so those stay hex.
 */
export const GAZETTEER_THEME = {
  id: "gazetteer",
  label: "Gazetteer",
  description: "Paper, walnut ink, stamp rust, Nest completion, and ledger chrome.",
  fonts: { sans: "source-sans-3", display: "newsreader", mono: "ibm-plex-mono" },
  // Newsreader names everything; regular weight below the page title, as in
  // the study kit. Source Sans 3 carries labels, Plex Mono the small figures.
  text: {
    wordmark: { slot: "display", weight: 600 },
    hero: { slot: "display", weight: 600 },
    title: { slot: "display", weight: 500 },
    heading: { slot: "display", weight: 400 },
    item: { slot: "display", weight: 400 },
    eyebrow: { slot: "sans", weight: 600, trackingEm: 0.12 },
    stat: { slot: "display", weight: 400 },
  },
  radiusRem: 0.75,
  // Warm near-white canvas with white cards; the paper tone (#f3ead8) is the
  // muted fill for tracks, inputs, and panels, so regions separate.
  colors: {
    background: "#fffdf8",
    foreground: "#241c14",
    card: "#ffffff",
    cardForeground: "#241c14",
    popover: "#ffffff",
    popoverForeground: "#241c14",
    primary: "#9a4f2c",
    primaryForeground: "#f8f1e3",
    secondary: "#e4e4e7",
    secondaryForeground: "#3f3f46",
    muted: "#f3ead8",
    mutedForeground: "#7a6a56",
    accent: "#e8d9c0",
    accentForeground: "#241c14",
    destructive: "#e2352e",
    border: "#e4d7bf",
    input: "#d4c4a4",
    ring: "#9a4f2c",
    page: "#fbf7ef",
    gain: "#4a6740",
    recover: "#eab308",
    warning: "#eab308",
    warningFill: "#fef9c3",
    // Sage second hue marks today and the selection; rust stays on actions.
    highlight: "#6f8175",
    highlightForeground: "#f8f1e3",
    today: "var(--gm-highlight)",
    todayForeground: "var(--gm-highlight-foreground)",
    daySelected: "color-mix(in srgb, var(--gm-highlight) 28%, var(--background))",
    daySelectedForeground: "var(--foreground)",
    // Opaque Zinc 300, one step darker than Original so the grey reads on paper.
    adjacent: "#d4d4d8",
    adjacentForeground: "oklch(0.36 0.01 286)",
    stampLight: "#c88968",
    heatmap0: "#efe4d0",
    heatmap1: "color-mix(in srgb, var(--primary) 28%, var(--background))",
    heatmap2: "var(--gm-stamp-light)",
    heatmap3: "var(--primary)",
    heatmap4: "#6e341c",
  },
  darkColors: {
    background: "#1c1610",
    foreground: "#f3ead8",
    card: "#241c14",
    cardForeground: "#f3ead8",
    popover: "#241c14",
    popoverForeground: "#f3ead8",
    primary: "#c88968",
    primaryForeground: "#1c1610",
    secondary: "#3f3f46",
    secondaryForeground: "#e4e4e7",
    muted: "#2a2218",
    mutedForeground: "#c4b49a",
    accent: "#3a2f24",
    accentForeground: "#f3ead8",
    destructive: "#ff6a65",
    border: "#5c4e3f",
    input: "#5c4e3f",
    ring: "#c88968",
    page: "#1c1610",
    gain: "#8aa37a",
    recover: "#facc15",
    warning: "#facc15",
    warningFill: "color-mix(in srgb, #facc15 22%, var(--background))",
    highlight: "#8aa396",
    highlightForeground: "#1c1610",
    today: "var(--gm-highlight)",
    todayForeground: "var(--gm-highlight-foreground)",
    daySelected: "color-mix(in srgb, var(--gm-highlight) 70%, var(--background))",
    daySelectedForeground: "var(--foreground)",
    adjacent: "#52525b",
    adjacentForeground: "oklch(0.92 0.003 286)",
    stampLight: "#8a5a40",
    heatmap0: "#2a2218",
    heatmap1: "color-mix(in srgb, var(--gm-stamp-light) 70%, var(--background))",
    heatmap2: "var(--gm-stamp-light)",
    heatmap3: "var(--primary)",
    heatmap4: "#e2c4b0",
  },
  effects: {
    landingAtmosphere: [
      "radial-gradient(1200px circle at 12% -8%, rgba(154, 79, 44, 0.12), transparent 55%)",
      "radial-gradient(900px circle at 92% 6%, rgba(212, 196, 164, 0.55), transparent 52%)",
      "radial-gradient(800px circle at 78% 88%, rgba(74, 103, 64, 0.12), transparent 50%)",
    ].join(", "),
  },
  themeColor: "#fbf7ef",
  backgroundColor: "#fbf7ef",
  statusBarStyle: "black-translucent",
  completionMark: "nest",
  tabChrome: "underline",
  remapDisplayColors: true,
} as const satisfies ThemeDefinition;
